# Generated by Django 4.1.3 on 2022-12-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='category/images')),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('ton', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arrow_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(default='')),
                ('characteristics', models.TextField(default='')),
                ('select_type', models.CharField(choices=[('mc', 'mobile_cranes'), ('cc', 'crawler_cranes'), ('lt', 'lowbed_trawls'), ('mp', 'modular_platforms')], default='mc', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.doc')),
            ],
        ),
        migrations.CreateModel(
            name='TypeTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='transport/images')),
                ('transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_images', to='products.transport')),
            ],
        ),
        migrations.AddField(
            model_name='transport',
            name='type_transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.typetransport'),
        ),
    ]
